[workspace]
members = [
    "common",
    "worker",
    "client",
]

[workspace.dependencies]
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
humantime = "2.1.0"

tokio = { version = "1.28.1", features = ["full"] }

lazy_static = "1.4"


monoio = "0.1.2"
monoio-compat = "0.1.0"


