version: '3.3'
services:
  fairy-worker:
    build: .
    hostname: fairy-worker
    ports:
      - '8080'
      - '19090'
    depends_on:
      - etcd
      - prom_pushgateway
      - prometheus
    environment:
      - FAIRY_CONFIG=/etc/fairy/fairy_config.toml
      - SERVICE_DISCOVERY_TYPE=etcd
      - ETCD_URIS=etcd:2379
      - METRICS_PUSH_URI=prom_pushgateway:9091
    volumes:
      - ./fairy_config.toml:/etc/fairy/fairy_config.toml
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    volumes:
      - ./conf/prometheus:/etc/prometheus
    ports:
      - '9090:9090'
  prom_pushgateway:
    image: prom/pushgateway:v1.2.0
    hostname: prom_pushgateway
    restart: unless-stopped
    ports:
      - '9091:9091'
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - ./conf/grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - '3000:3000'

  etcd:
    image: 'bitnami/etcd:latest'
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
      