version: '3.3'
services:
  fairy-worker:
    build: .
    hostname: fairy-worker
    ports:
      - '8080'
      - '19090'
    depends_on:
      - etcd
    environment:
      - FAIRY_CONFIG=/etc/fairy/fairy_config.toml
      - SERVICE_DISCOVERY_TYPE=etcd
      - ETCD_URIS=etcd:2379
    volumes:
      - ./fairy_config.toml:/etc/fairy/fairy_config.toml
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    volumes:
      - ./conf/prometheus:/etc/prometheus
    ports:
      - '9090:9090'
  etcd:
    image: 'bitnami/etcd:latest'
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380