[package]
name = "fairy-runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "fairy_runtime"
crate-type = ["lib"]
path = "src/runtime_lib.rs"

[dependencies]
io-uring = "0.6"
libc = "0.2.147"
log = "0.4.20"
tempfile = "3.8.1"

[features]
iouring=[]
default=["iouring"]