global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  # - job_name: fairy_worker
  #   static_configs:
  #     - targets: ['fairy-worker:8080']
  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['prom_pushgateway:9091']