[package]
name = "fairy-fuse"
version = "0.1.0"
edition = "2021"

[lib]
name = "fairy_fuse"
crate-type = ["lib"]
path = "src/fuse_lib.rs"

[dependencies]
# mountpoint-s3 = { git = "https://github.com/beinan/mountpoint-s3.git", branch = "main" }
