[package]
name = "fairy-fuse"
version = "0.1.0"
edition = "2021"

[lib]
name = "fairy_fuse"
crate-type = ["lib"]
path = "src/fuse_lib.rs"

[dependencies]
log = { workspace= true }

fuser = {git = "https://github.com/beinan/fuser.git", branch = "master"}
fuse_mt = "0.6.0"
libc = "0.2.147"